spring:
  application:
    name: basic2
  output:
    ansi:
      enabled: always
  profiles:
    active: test
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  datasource:
#    # 데이터베이스 연결 URL
#    url: jdbc:mariadb://localhost:3306/qnaService?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
#    username: root
#    password:
#    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true